spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # oracle 예약어를 테이블명으로 사용
        globally_quoted_identifiers: true
    show-sql: true
    database: oracle

  profiles:
    include: jelly

  # DB 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1523:xe
    username: bootuser
    password: bootuser

  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

# jwt
application:
  security:
    jwt:
      secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
      expiration: 900000 # 15m
      refreshExpiration: 86400000 # 24h

logging:
  level:
    org.springframework.security: DEBUG